name: flutter_cinema
description: A Flutter Cinema App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.1
  flutter_riverpod: ^0.14.0+2
  dio: ^4.0.0
  extended_image: ^4.0.1
  intl: ^0.17.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  json_serializable:
  freezed: ^0.14.2
  build_runner:

flutter:

  uses-material-design: true
